### ISSUE TITLE
¿Cuál es la diferencia entre notas 01 y 02 y 03?

### ISSUE THREAD

**Issue by lcolladotor** [Melii99/rnaseq_2023_notas#1]
Hola @Melii99,

¿Cuál es la diferencia entre notas 01 y 02 y 03?
https://github.com/Melii99/rnaseq_2023_notas/tree/master/R (específicamente en esta versión: https://github.com/Melii99/rnaseq_2023_notas/tree/5b4d84125594e90ca1cb4740a61a9ad091035cf8/R)

Como los nombres de tus archivos no son únicos, entonces necesitas documentar que contiene cada uno. Eso es parte de lo que intentamos evitar al usar nombres de archivo como `01_intro.R` y `02_recount3.R` por decir algo, donde sabemos el orden gracias a los números (`01_` y `02_`) y también de que se trata cada script gracias a los nombres únicos (`intro.R` y `recount3.R`).

Esto es parte de https://github.com/LieberInstitute/template_project.

Saludos,
Leo

**Comment by Melii99** [comment]
Gracias por el comentario. 
2 preguntas, ¿Sería más recomendable cambiar los nombres de los archivos para especificar que corresponden al número de sesión o documentarlos? y ¿en caso de la documentación, sería preferible en un archivo readme en la carpeta o documentar dentro de cada script de R?
Saludos!

**Comment by lcolladotor** [comment]
Es más sencillo cambiar los nombres y dejar los números como 01, 02, etc. Los números especifican el orden, pero el nombre, ayudaría a entender de que se trata. Hacer un README.md toma más energía y hay que andarlo actualizando continuamente, mientras que los nombres de los archivos generalmente se quedan estáticos y solo los tienes que especificar al momento de crearlos.

**Comment by Melii99** [comment]
Gracias, ya quedaron renombrados los archivos.
